import argparse

def parse_args():
    p = argparse.ArgumentParser(description="Async raw bbox track + raw inference overlay + calibrated BEV depth geometry")
    p.add_argument("--config", type=str, required=True)
    p.add_argument("--encoder-model", type=str, required=True, help="Encoder file: .pt, .onnx, or .engine")
    p.add_argument("--classifier-model", type=str, required=True, help="Classifier file: .pt, .onnx, or .engine")
    p.add_argument("--video", type=str, default=None)
    p.add_argument("--output", type=str)
    p.add_argument("--bbox-csv", type=str, default=None, help="optional framewise bbox CSV; if omitted, use YOLO tracking")
    p.add_argument("--detector", type=str, default="yolo26n.pt")
    p.add_argument("--tracker", type=str, default="bytetrack.yaml")
    p.add_argument("--detector-conf", type=float, default=0.25)
    p.add_argument("--max-boxes", type=int, default=10)
    p.add_argument("--sweep-idx", type=int, default=1)
    p.add_argument("--device", type=str, default="cuda:0")
    p.add_argument("--display", action="store_true")
    p.add_argument("--no-fp16", action="store_true")
    p.add_argument("--stride-overlap", type=float, default=0.10)
    p.add_argument("--render-scale", type=float, default=1.0)
    p.add_argument("--detector-imgsz", type=int, default=640)
    p.add_argument("--anticipation-time", type=float, default=1.0)
    p.add_argument("--save-bev-video", action="store_true")
    p.add_argument("--bev-size", type=int, default=700)

    p.add_argument("--use-depth", action="store_true")
    p.add_argument("--depth-model", type=str, default=None, help="DepthAnything .onnx/.engine file location")
    p.add_argument("--depth-every-n", type=int, default=4)
    p.add_argument("--depth-calib-interval-sec", type=float, default=3.0)
    p.add_argument("--depth-scale-alpha", type=float, default=0.8)
    p.add_argument("--depth-min-calib-points", type=int, default=1)
    p.add_argument("--depth-sample-step", type=int, default=20)
    p.add_argument("--depth-max-points", type=int, default=12000)
    p.add_argument("--depth-smooth-alpha", type=float, default=0.1, help="Temporal smoothing factor for depth maps. Lower = smoother.")

    return p.parse_args()
